/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/K79j1khmrxM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Progress } from "@/components/ui/progress"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs"

export function test2() {
  return (
    <div className="flex">
      <aside className="w-64 h-screen p-4 bg-gray-100">
        <div className="flex items-center mb-8">
          <MenuIcon className="w-6 h-6 mr-2" />
          <span className="text-lg font-semibold">Versetta</span>
        </div>
        <nav className="space-y-2">
          <Link href="#" className="block p-2 text-gray-900 bg-gray-200 rounded-md" prefetch={false}>
            <HomeIcon className="w-5 h-5 mr-2 inline" />
            Home
          </Link>
          <Link href="#" className="block p-2 text-gray-900 rounded-md" prefetch={false}>
            <FolderIcon className="w-5 h-5 mr-2 inline" />
            Projects
          </Link>
          <Link href="#" className="block p-2 text-gray-900 rounded-md" prefetch={false}>
            <SquareCheckIcon className="w-5 h-5 mr-2 inline" />
            Tasks
          </Link>
          <Link href="#" className="block p-2 text-gray-900 rounded-md" prefetch={false}>
            <MessageSquareIcon className="w-5 h-5 mr-2 inline" />
            Comments
          </Link>
          <Link href="#" className="block p-2 text-gray-900 rounded-md" prefetch={false}>
            <DatabaseIcon className="w-5 h-5 mr-2 inline" />
            Storage
          </Link>
          <Link href="#" className="block p-2 text-gray-900 rounded-md" prefetch={false}>
            <FilmIcon className="w-5 h-5 mr-2 inline" />
            Production
          </Link>
          <Link href="#" className="block p-2 text-gray-900 rounded-md" prefetch={false}>
            <BarChart2Icon className="w-5 h-5 mr-2 inline" />
            Analyzer
          </Link>
        </nav>
      </aside>
      <main className="flex-1 p-6 bg-white">
        <header className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-semibold">Dashboard</h1>
          <div className="flex items-center space-x-4">
            <Input type="search" placeholder="Search..." className="w-64" />
            <Button variant="ghost" size="icon">
              <BellIcon className="w-6 h-6" />
            </Button>
            <Avatar>
              <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
              <AvatarFallback>U</AvatarFallback>
            </Avatar>
          </div>
        </header>
        <div className="grid grid-cols-3 gap-6 mb-6">
          <Card>
            <CardHeader className="flex justify-between">
              <div>
                <CardTitle className="text-lg font-semibold text-blue-600">Videos in Production</CardTitle>
                <CardDescription className="text-3xl font-bold">12</CardDescription>
                <p className="text-sm text-blue-600">+2 from last week</p>
              </div>
              <VideoIcon className="w-6 h-6 text-blue-600" />
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="flex justify-between">
              <div>
                <CardTitle className="text-lg font-semibold text-blue-600">Views on Last Video</CardTitle>
                <CardDescription className="text-3xl font-bold">54,231</CardDescription>
                <p className="text-sm text-blue-600">+20% from last video</p>
              </div>
              <EyeIcon className="w-6 h-6 text-blue-600" />
            </CardHeader>
          </Card>
          <Card>
            <CardHeader className="flex justify-between">
              <div>
                <CardTitle className="text-lg font-semibold text-blue-600">Next Project Progress</CardTitle>
                <CardDescription className="text-3xl font-bold">68%</CardDescription>
              </div>
              <PlusIcon className="w-6 h-6 text-blue-600" />
            </CardHeader>
            <CardContent>
              <Progress value={68} className="w-full" />
            </CardContent>
          </Card>
        </div>
        <div className="grid grid-cols-2 gap-6">
          <Card>
            <CardHeader className="flex justify-between items-center">
              <CardTitle className="text-xl font-semibold">Projects</CardTitle>
              <Button variant="default" className="bg-primary text-primary-foreground px-4 py-2">
                + Add New Project
              </Button>
            </CardHeader>
            <CardContent>
              <div className="p-4 bg-gray-100 rounded-md">
                <h3 className="text-lg font-semibold">Is it the first project</h3>
                <div className="flex items-center mb-2">
                  <Switch id="progress" />
                  <Label htmlFor="progress" className="ml-2">
                    In Progress
                  </Label>
                </div>
                <p>Project ID: 1</p>
                <p>Team ID: 1</p>
                <p>Creator ID: 1</p>
                <div className="mt-2">
                  <Input placeholder="Details" />
                </div>
                <div className="mt-4">
                  <p>Current: active</p>
                  <Progress value={38} className="w-full" />
                  <p className="text-sm">38% Complete</p>
                  <p>Expected Publish: August 21, 2024</p>
                </div>
              </div>
            </CardContent>
            <CardFooter className="flex justify-end space-x-2">
              <Button variant="outline">Edit</Button>
              <Button variant="default" className="bg-green-600">
                Publish
              </Button>
              <Button variant="destructive">Delete</Button>
              <Button variant="default">Expand</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader className="flex justify-between items-center">
              <CardTitle className="text-xl font-semibold">Tasks</CardTitle>
              <Button variant="default" className="bg-primary text-primary-foreground px-4 py-2">
                + Add New Task
              </Button>
            </CardHeader>
            <CardContent>
              <Tabs>
                <TabsList>
                  <TabsTrigger value="all">All</TabsTrigger>
                  <TabsTrigger value="pending">Pending</TabsTrigger>
                  <TabsTrigger value="assigned">Assigned</TabsTrigger>
                </TabsList>
                <TabsContent value="all">
                  <div className="space-y-4">
                    <div className="p-4 bg-gray-100 rounded-md">
                      <div className="flex justify-between">
                        <div>
                          <h4 className="text-lg font-semibold">First task updated</h4>
                          <p>Project ID: N/A, Team ID: 1, Creator ID: 1</p>
                          <p>Due: 8/21/2024</p>
                          <p>Let's gooo</p>
                        </div>
                        <div className="flex space-x-2">
                          <Button variant="outline" size="icon">
                            <FilePenIcon className="w-4 h-4" />
                          </Button>
                          <Button variant="destructive" size="icon">
                            <TrashIcon className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                    <div className="p-4 bg-gray-100 rounded-md">
                      <div className="flex justify-between">
                        <div>
                          <h4 className="text-lg font-semibold">ABD</h4>
                          <p>Project ID: 1, Team ID: 1, Creator ID: 1</p>
                          <p>Uref</p>
                        </div>
                        <div className="flex space-x-2">
                          <Button variant="outline" size="icon">
                            <FilePenIcon className="w-4 h-4" />
                          </Button>
                          <Button variant="destructive" size="icon">
                            <TrashIcon className="w-4 h-4" />
                          </Button>
                        </div>
                      </div>
                    </div>
                  </div>
                </TabsContent>
              </Tabs>
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}

function BarChart2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="18" x2="18" y1="20" y2="10" />
      <line x1="12" x2="12" y1="20" y2="4" />
      <line x1="6" x2="6" y1="20" y2="14" />
    </svg>
  )
}


function BellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function DatabaseIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function EyeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}


function FilePenIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function FilmIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M7 3v18" />
      <path d="M3 7.5h4" />
      <path d="M3 12h18" />
      <path d="M3 16.5h4" />
      <path d="M17 3v18" />
      <path d="M17 7.5h4" />
      <path d="M17 16.5h4" />
    </svg>
  )
}


function FolderIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>
  )
}


function HomeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MessageSquareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SquareCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}


function VideoIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5" />
      <rect x="2" y="6" width="14" height="12" rx="2" />
    </svg>
  )
}
